railstutorials_org: https://www.railstutorial.org/
learn_enough_tutorials: https://www.learnenough.com/
tutorials_book: https://www.railstutorial.org/book
screencast_tutorials: https://screencasts.railstutorial.org/
rubyonrails_org: https://rubyonrails.org/
rails_help: https://www.railstutorial.org/help
author: http://www.michaelhartl.com/
news_railstutorial: http://news.railstutorial.org/
